"""Test the conversation fix."""

import asyncio
import os
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

from src.models.conversation import Conversation
from src.database.connection_pool import ConnectionPool
from src.database.config import get_database_config
from src.repositories.conversation_repository import ConversationRepository
from src.repositories.conversation_vector_repository import ConversationVectorRepository
from src.memory.local_embedding_client import LocalEmbeddingClient


async def test_conversation_creation():
    """Test creating conversations and vectors."""
    print("=" * 60)
    print("Testing Conversation Creation Fix")
    print("=" * 60)

    # Initialize database connection
    db_config = get_database_config()
    pool = ConnectionPool(db_config)
    await pool.initialize()

    # Initialize repositories
    conversation_repo = ConversationRepository(pool)
    vector_repo = ConversationVectorRepository(pool)

    # Initialize embedding client
    os.environ["HF_ENDPOINT"] = "https://hf-mirror.com"
    embedding_client = LocalEmbeddingClient(
        model_name="moka-ai/m3e-base",
        dimensions=768,
        device="cpu"
    )

    # Test creating a conversation without conversation_id
    print("\n[Test 1] Creating conversation without ID")
    try:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        new_conversation = Conversation(
            conversation_id=None,  # No ID - will be generated by database
            user_id=6583134502,  # Use existing user ID from database
            group_id=None,
            role="user",
            content="This is a test message",
            timestamp=timestamp,
            message_id=None,
            style_id=None,
        )

        print(f"Before save: conversation_id = {new_conversation.conversation_id}")

        # Save to database
        created_conversation = await conversation_repo.create(new_conversation)

        print(f"After save: conversation_id = {created_conversation.conversation_id}")

        if created_conversation.conversation_id is not None:
            print("[SUCCESS] Conversation ID generated successfully!")

            # Now test creating a vector for this conversation
            print("\n[Test 2] Creating vector for the conversation")
            try:
                embedding = await embedding_client.generate_embedding(new_conversation.content)
                vector_id = f"vec_{created_conversation.conversation_id}_test"

                await vector_repo.create(
                    created_conversation.conversation_id,
                    embedding,
                    vector_id
                )

                print("[SUCCESS] Vector created successfully!")
                print(f"Conversation ID: {created_conversation.conversation_id}")
                print(f"Vector ID: {vector_id}")
                print(f"Embedding shape: {embedding.shape}")

                # Clean up test data
                print("\n[Cleanup] Removing test data")
                await vector_repo.delete_by_conversation_id(created_conversation.conversation_id)
                await conversation_repo.delete(created_conversation.conversation_id)
                print("[SUCCESS] Test data cleaned up")

                return True

            except Exception as e:
                print(f"[ERROR] Failed to create vector: {e}")
                return False
        else:
            print("[ERROR] Conversation ID was not generated!")
            return False

    except Exception as e:
        print(f"[ERROR] Failed to create conversation: {e}")
        import traceback
        traceback.print_exc()
        return False
    finally:
        await pool.close()


if __name__ == "__main__":
    success = asyncio.run(test_conversation_creation())
    if success:
        print("\n" + "=" * 60)
        print("[SUCCESS] All tests passed!")
        print("The foreign key constraint issue is fixed.")
        print("=" * 60)
    else:
        print("\n" + "=" * 60)
        print("[FAIL] Tests failed!")
        print("=" * 60)
