"""Simple test of the conversation fix."""

import asyncio
import os
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

from src.models.conversation import Conversation
from src.database.connection_pool import ConnectionPool
from src.database.config import get_database_config
from src.repositories.conversation_repository import ConversationRepository


async def test_simple():
    """Simple test of conversation ID generation."""
    print("=" * 60)
    print("Simple Conversation Fix Test")
    print("=" * 60)

    # Initialize database connection
    db_config = get_database_config()
    pool = ConnectionPool(db_config)
    await pool.initialize()

    # Initialize repository
    conversation_repo = ConversationRepository(pool)

    try:
        # Test creating a conversation without ID
        print("\n[Test] Creating conversation with conversation_id=None")
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        new_conversation = Conversation(
            conversation_id=None,  # Key fix: None instead of 0
            user_id=6583134502,  # Existing user
            group_id=None,
            role="user",
            content="Testing the fix",
            timestamp=timestamp,
            message_id=None,
            style_id=None,
        )

        print(f"Before save: conversation_id = {new_conversation.conversation_id}")

        # Save to database
        created_conversation = await conversation_repo.create(new_conversation)

        print(f"After save: conversation_id = {created_conversation.conversation_id}")

        # Verify the fix worked
        if created_conversation.conversation_id is not None and created_conversation.conversation_id > 0:
            print(f"\n[SUCCESS] Foreign key constraint fix is working!")
            print(f"Generated conversation_id: {created_conversation.conversation_id}")

            # Clean up
            await conversation_repo.delete(created_conversation.conversation_id)
            print("[Cleanup] Test data removed")

            return True
        else:
            print("\n[FAIL] conversation_id was not generated properly")
            return False

    except Exception as e:
        print(f"\n[ERROR] {e}")
        return False
    finally:
        await pool.close()


if __name__ == "__main__":
    success = asyncio.run(test_simple())
    print("\n" + "=" * 60)
    if success:
        print("[SUCCESS] The foreign key constraint issue is FIXED!")
        print("Conversation IDs are now properly generated by the database.")
    else:
        print("[FAIL] Fix validation failed")
    print("=" * 60)
